username=auction_system
password=Auction@Group7
jdbcUrl=jdbc:mysql://217.15.163.37:3306/auction_system?autoReconnect=true&useSSL=false
maximumPoolSize=20
minimumIdle=5
connectionTimeout=30000
maxLifetime=1800000
keepaliveTime=60000
connectionTestQuery=SELECT 1