server.port=8080

spring.datasource.url=jdbc:mysql://217.15.163.37:3306/auction_system
spring.datasource.username=auction_system
spring.datasource.password=Auction@Group7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

app.storage.root=E:/Java/BigAssignment---Group-7/storage
app.storage.avatars=${app.storage.root}/avatars
app.storage.items=${app.storage.root}/items