server.port=8080

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.goaiuzhggdlwtfuibmsl&password=o1iBsDFXqTPMWeup
spring.datasource.username=postgres
spring.datasource.password=o1iBsDFXqTPMWeup
spring.datasource.driver-class-name=org.postgresql.Driver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging.level.root=INFO
logging.level.org.springframework.web=INFO

app.storage.root=./storage
app.storage.avatars=${app.storage.root}/avatars
app.storage.items=${app.storage.root}/items

spring.output.ansi.enabled=always
