username=auction_system
password=Auction@Group7
jdbcUrl=jdbc:mysql://217.15.163.37:3306/auction_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

maximumPoolSize=20
minimumIdle=5
maxLifetime=600000
idleTimeout=300000
keepaliveTime=30000
connectionTimeout=30000
connectionTestQuery=SELECT 1