# Supabase Database Credentials
username=postgres
password=o1iBsDFXqTPMWeup

# The JDBC connection string
jdbcUrl=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.goaiuzhggdlwtfuibmsl&password=o1iBsDFXqTPMWeup

# Connection Pool Settings
maximumPoolSize=20
minimumIdle=5
maxLifetime=600000
idleTimeout=300000
keepaliveTime=30000
connectionTimeout=30000
